name: brewlytics_dbt
version: '1.0'
config-version: 2

profile: brewlytics

seeds:
  brewlytics_dbt:
    +quote_columns: false
    +pre-hook:
      - "truncate table {{ target.schema }}.order_items, {{ target.schema }}.orders, {{ this }}"
