oltp:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('OLTP_HOST', 'oltp-db') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: {{ env_var('OLTP_PORT', '5432') }}
      dbname: "{{ env_var('OLTP_DB') }}"
      schema: public

olap:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('OLAP_HOST', 'olap-db') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: {{ env_var('OLAP_PORT', '5432') }}
      dbname: "{{ env_var('OLAP_DB') }}"
      schema: public
