oltp:
  target: dev
  outputs:
    dev:
      type: postgres
      host: oltp-db
      user: brew
      password: brew
      port: 5432
      dbname: coffee_oltp
      schema: public

olap:
  target: dev
  outputs:
    dev:
      type: postgres
      host: olap-db
      user: brew
      password: brew
      port: 5432
      dbname: coffee_olap
      schema: public
