version: '3.9'
services:
  oltp-db:
    image: postgres:14
    environment:
      POSTGRES_USER: brew
      POSTGRES_PASSWORD: brew
      POSTGRES_DB: coffee_oltp
    ports:
      - "5432:5432"

  flyway-oltp:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/migrations/oltp:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://oltp-db:5432/coffee_oltp
      FLYWAY_USER: brew
      FLYWAY_PASSWORD: brew
    depends_on:
      - oltp-db

  dbt-oltp:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    environment:
      DBT_PROFILES_DIR: /dbt
      DBT_PROFILE: oltp
      DBT_TARGET: dev
    entrypoint: ["/bin/sh", "-c", "./dbt_oltp.sh"]
    depends_on:
      - flyway-oltp

  olap-db:
    image: postgres:14
    environment:
      POSTGRES_USER: brew
      POSTGRES_PASSWORD: brew
      POSTGRES_DB: coffee_olap
    ports:
      - "5433:5432"

  flyway-olap:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/migrations/olap:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://olap-db:5432/coffee_olap
      FLYWAY_USER: brew
      FLYWAY_PASSWORD: brew
    depends_on:
      - olap-db

  dbt-olap:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    environment:
      DBT_PROFILES_DIR: /dbt
      DBT_PROFILE: olap
      DBT_TARGET: dev
    entrypoint: ["/bin/sh", "-c", "./dbt_olap.sh"]
    depends_on:
      - flyway-olap

  order-api:
    build: ./order-api
    deploy:
      replicas: 3
    environment:
      OLTP_HOST: oltp-db
      OLTP_PORT: 5432
      OLTP_DB: coffee_oltp
      OLTP_USER: brew
      OLTP_PASSWORD: brew
    depends_on:
      - flyway-oltp

  product-api:
    build: ./product-api
    environment:
      OLTP_HOST: oltp-db
      OLTP_PORT: 5432
      OLTP_DB: coffee_oltp
      OLTP_USER: brew
      OLTP_PASSWORD: brew
    depends_on:
      - flyway-oltp

  customer-api:
    build: ./customer-api
    environment:
      OLTP_HOST: oltp-db
      OLTP_PORT: 5432
      OLTP_DB: coffee_oltp
      OLTP_USER: brew
      OLTP_PASSWORD: brew
    depends_on:
      - flyway-oltp

  gateway:
    build: ./gateway
    depends_on:
      - order-api
      - product-api
      - customer-api
    ports:
      - "8000:80"

  airflow:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./airflow-pipeline/dags:/opt/airflow/dags
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com && airflow scheduler & airflow webserver"
    ports:
      - "8080:8080"
    depends_on:
      - flyway-oltp
      - flyway-olap

  metabase:
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: olap-db
      MB_DB_USER: brew
      MB_DB_PASS: brew
    ports:
      - "3000:3000"
    depends_on:
      - flyway-olap

  k6:
    image: grafana/k6
    volumes:
      - ./k6-loadtest:/scripts
    entrypoint: "k6 run /scripts/loadtest.js"
    depends_on:
      - gateway

